### PR TITLE
Add ability to use custom completing-read function

### PR DESCRIPTION
**Pull request by jojojames**
Usage ->   (setq xcode-completing-read-function 'ivy-completing-read)

Sample screenshot with ivy-completing-read.

completingread

### CODE REVIEW

**Comment by nicklanasa** [comment]
Looks good. Merge whenever. What font are you using btw?

**Comment by nicklanasa** [comment]
I don't use ivy but I think it might be nice to update the `README.md` with the usage? What do you think?

**Comment by jojojames** [comment]
> Merge whenever.

Do you mean I can merge somehow? I don't see the UI for it.

> What font are you using btw? 

https://github.com/madmalik/mononoki

> I don't use ivy but I think it might be nice to update the README.md with the usage? What do you think? 

Yeah, do you prefer the readme update in the same commit or after the pull goes through?

**Comment by nicklanasa** [comment]
Lol, I forgot I was the only one that could merge pull requests. 

You can do it in the same commit or a separate one. Just do it in this pull request.

**Comment by jojojames** [comment]
Done

**Pull request merged**
