### PR TITLE
Melpa, travis-ci, and consolidation

### PR DESCRIPTION
**Pull request by nicklanasa**
- Merged all functions into `xcode-mode.el`. 
- All actions start with `C-c x` now. This is how minor modes are suppose to function.
- Updated tests.
- Travis-ci integration.
- Updated `README.md`.
- Updated Xcode test projects.

### CODE REVIEW

**Comment by purcell** [comment]
Nice! `C-c x` is still a reserved binding, though, for end-user customisation, so you should choose a different option. The [manual page](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) has some guidelines for what's permissible for minor modes.

**Comment by nicklanasa** [comment]
@jojojames Any preference for minor mode key binding?

**Comment by nicklanasa** [comment]
How about `C-M-x` then two letter Xcode action? So, in the case for building Xcode projects, `C-M-x bb`?

**Comment by jojojames** [comment]
I use evil bindings so I just took whatever you used for the binds and prefixed with <SPC>u(bind).

```
(bind-map xcode-leader-map
  :evil-keys ("SPC")
  :evil-states (normal motion visual)
  :major-modes (objc-mode)
  :minor-modes (xcode-mode))
(bind-keys :map xcode-leader-map
           ("uu" . xcode-xctool-build-and-run)
           ("urr" . xcode-xctool-run)
           ("ubb" . xcode-xctool-build)
           ("ubt" . xcode-xctool-build-tests)
           ("utr" . xcode-xctool-run-tests)
           ("utt" . xcode-xctool-test)
           ("uto" . xcode-xctool-build-tests-only)
           ("ucc" . xcode-xctool-clean)
           ("upi" . xcode-pod-install)
           ("uos" . xcode-open-storyboard)
           ("uop" . xcode-open-project)
           ("uow" . xcode-open-workspace)
           ("uaa" . xcode-xctool-archive)
           ("udd" . xcode-delete-derived-data))
```

**Comment by nicklanasa** [comment]
@purcell PR Updated

**Pull request merged**
